name: Fetch and Display Idira Secret

on:
  push:
    branches:
      - main
  workflow_dispatch:

# CRITICAL: id-token: write is required for GitHub to issue the J
permissions:
  id-token: write
  contents: read

jobs:
  fetch-and-display:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Secret from Idira Secrets Manager
        uses: cyberark/conjur-action@v2.0.12
        with:
          url: ${{ secrets.IDIRA_URL }}
          account: ${{ secrets.IDIRA_ACCOUNT }} 
          authn_id: github
          # Syntax is "Safe_Name/Secret_Name|Local_Environment_Variable"
          secrets: |
            data/vault/SM-AWS-SecretHub/aws-dummy-account/username|MY_MAPPED_SECRET;data/vault/SM-AWS-SecretHub/aws-dummy-account/password|MY_SECOND_SECRET
            

      - name: Display the Secret
        run: |
          echo "Secret successfully pulled from Idira Secrets Manager SaaS!"
          
          echo "The vaulted username is:"
          echo "$MY_MAPPED_SECRET" | sed 's/./& /g'
          
          echo "The vaulted password is:"
          echo "$MY_SECOND_SECRET" | sed 's/./& /g'
